# -*- coding: utf-8 -*-
"""build_vector_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzNfwFE4rl0k2EVHjvO1c3cWCaghp4VI
"""

pip install pandas chromadb sentence-transformers tqdm

import pandas as pd
import chromadb
from chromadb.utils import embedding_functions
from tqdm import tqdm
import json
import os

# Configuration
DATA_FILE = "dataset.csv"
DB_DIR = "./chroma_db"
COLLECTION_NAME = "financial_rag"
MODEL_NAME = "all-MiniLM-L6-v2"

# Chunking settings
CHUNK_SIZE = 800
OVERLAP = 100

def load_data(filepath):
    if not os.path.exists(filepath):
        print(f"Error: File {filepath} not found.")
        return None

    print(f"Loading data from {filepath}...")
    df = pd.read_csv(filepath)

    # Basic cleaning: remove empty summaries
    df = df.dropna(subset=["DetailedSummary"])
    df = df.drop_duplicates(subset=["DetailedSummary"])

    print(f"Data loaded: {len(df)} rows.")
    return df

def get_text_chunks(text, size, overlap):
    # Simple sliding window chunking
    chunks = []
    start = 0
    while start < len(text):
        end = start + size
        chunk = text[start:end]

        # Skip small artifacts
        if len(chunk.strip()) > 50:
            chunks.append(chunk)

        start = end - overlap
    return chunks

def process_dataset(df):
    print("Processing documents and extracting metadata...")
    processed_docs = []

    for i, row in tqdm(df.iterrows(), total=len(df)):
        # Combine fields for better context
        content = f"Title: {row['Subject']}\nDate: {row['Date']}\nContent: {row['DetailedSummary']}\nImpact: {row['Impact']}"

        chunks = get_text_chunks(content, CHUNK_SIZE, OVERLAP)

        # Save metadata for citations later
        meta = {
            "source_id": f"doc_{i}",
            "title": str(row['Subject']),
            "date": str(row['Date']),
            "impact": str(row['Impact'])
        }

        for j, chunk_text in enumerate(chunks):
            processed_docs.append({
                "id": f"doc_{i}_chunk_{j}",
                "text": chunk_text,
                "metadata": meta
            })

    # Save a local backup just in case
    with open("processed_chunks.json", "w", encoding="utf-8") as f:
        json.dump(processed_docs, f, indent=2, ensure_ascii=False)

    print(f"Processed {len(processed_docs)} chunks. Saved to json.")
    return processed_docs

def build_db(chunks):
    print(f"Initializing ChromaDB at {DB_DIR}...")
    client = chromadb.PersistentClient(path=DB_DIR)

    embedding_func = embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name=MODEL_NAME
    )

    # Reset collection if it exists to ensure fresh start
    try:
        client.delete_collection(name=COLLECTION_NAME)
    except:
        pass

    collection = client.create_collection(
        name=COLLECTION_NAME,
        embedding_function=embedding_func,
        metadata={"hnsw:space": "cosine"}
    )

    # Batch add to avoid memory issues
    batch_size = 100
    print("Indexing chunks...")

    for i in tqdm(range(0, len(chunks), batch_size)):
        batch = chunks[i : i + batch_size]

        collection.add(
            ids=[item["id"] for item in batch],
            documents=[item["text"] for item in batch],
            metadatas=[item["metadata"] for item in batch]
        )

    print(f"Database built. Total count: {collection.count()}")
    return collection

def check_db(collection):
    # Quick sanity check
    print("\nRunning test query...")
    results = collection.query(query_texts=["dividend"], n_results=1)

    if results['documents']:
        print("Match found:")
        print(f"Source: {results['metadatas'][0][0]['title']}")
        print(f"Text: {results['documents'][0][0][:100]}...")
    else:
        print("No results found.")

if __name__ == "__main__":
    df = load_data(DATA_FILE)
    if df is not None:
        chunks = process_dataset(df)
        col = build_db(chunks)
        check_db(col)

